using ProjectManager.DomainModel.Models.Enums;
using System.ComponentModel.DataAnnotations;
using Comments = ProjectManager.API.Utilities.Comments;

namespace ProjectManager.Services.DTOs
{
    public class ProjectObjectForCreationDto
    {
        //[Required(ErrorMessage = "You should provide a name value for the project object.")]
        public string Name { get; set; } = string.Empty;

        //[MaxLength(500)]
        public string? Description { get; set; }

        public int SprintNumber { get; set; }

        //[Required]
        //Autogenerated? Where are these data processing handled?
        //in serviceLayer
        public DateTime CreatedAt { get; set; }

        [Required(ErrorMessage = "You should provide an email.")]
        public string? CreatedBy { get; set; }

        //?
        public DateTime? UpdatedAt { get; set; }

        public string? UpdatedBy { get; set; }

        public string? Assignee { get; set; }

        //[Required(ErrorMessage = "You should provide a status for this project object.")]
        //Like this from Enum or String and validations are done in somewhere else?
        public Status Status { get; set; }

        //public ICollection<ProjectObjectHistory> ProjectObjectHistory { get; set; } = new List<ProjectObjectHistory>();
        //public ICollection<ProjectObjectRelation> ProjectObjectRelations { get; set; } = new List<ProjectObjectRelation>();
        //public ICollection<ProjectObjectRelation> RelatedProjectObjectRelations { get; set; } = new List<ProjectObjectRelation>();

        public ICollection<Comments> Comments { get; set; } = new List<Comments>();
    }
}
